USE [master]
GO

DECLARE @DbName varchar(60) = 'KeplerNew'; 
DECLARE @COMMAND_TEMPLATE VARCHAR(MAX)
DECLARE @SQL_SCRIPT VARCHAR(MAX)

set @DbName = QUOTENAME(@DbName)


EXEC('CREATE DATABASE '+ @DbName)


SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET  READ_WRITE '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
GO




