USE [master]
GO

DECLARE @DbName varchar(60) = 'KeplerNew'
DECLARE @COMMAND_TEMPLATE VARCHAR(MAX)
DECLARE @SQL_SCRIPT VARCHAR(MAX)
DECLARE @USE_DB_TEMPLATE varchar(60) 
DECLARE @USE_DB_SCRIPT VARCHAR(60)

set @DbName = QUOTENAME(@DbName)

EXEC('CREATE DATABASE '+ @DbName)


SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET ANSI_NULL_DEFAULT OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)

SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET ANSI_NULLS OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)

SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET ANSI_PADDING OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET ANSI_WARNINGS OFF  '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET ARITHABORT OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET AUTO_CLOSE OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET AUTO_SHRINK OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET AUTO_UPDATE_STATISTICS ON '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET CURSOR_CLOSE_ON_COMMIT OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET CURSOR_DEFAULT  GLOBAL '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET CONCAT_NULL_YIELDS_NULL OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)

SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME}  SET NUMERIC_ROUNDABORT OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET QUOTED_IDENTIFIER OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET RECURSIVE_TRIGGERS OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET  DISABLE_BROKER '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET AUTO_UPDATE_STATISTICS_ASYNC OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET DATE_CORRELATION_OPTIMIZATION OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)

SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME}  SET TRUSTWORTHY OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET ALLOW_SNAPSHOT_ISOLATION OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET PARAMETERIZATION SIMPLE '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET READ_COMMITTED_SNAPSHOT ON '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)

SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME}  SET HONOR_BROKER_PRIORITY OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)

SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME}  SET RECOVERY FULL '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET  MULTI_USER '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)

SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET PAGE_VERIFY CHECKSUM  '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET DB_CHAINING OFF '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)

SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME}  SET TARGET_RECOVERY_TIME = 0 SECONDS '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)
 
SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET DELAYED_DURABILITY = DISABLED '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)


/****** Object:  Table [dbo].[BaseLines]    Script Date: 5/31/2016 8:42:14 PM ******/

SET @COMMAND_TEMPLATE='USE {DBNAME};
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON


CREATE TABLE {DBNAME}.[dbo].[BaseLines](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[BranchId] [bigint] NOT NULL,
	[Name] [nvarchar](700) NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_dbo.BaseLines] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]'

SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)


/****** Object:  Table [dbo].[Builds]    Script Date: 5/31/2016 8:42:14 PM ******/
SET @COMMAND_TEMPLATE='USE {DBNAME};
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON


CREATE TABLE {DBNAME}.[dbo].[Builds](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[StartDate] [datetime] NULL,
	[StopDate] [datetime] NULL,
	[Duration] [time](7) NULL,
	[PredictedDuration] [time](7) NULL,
	[BranchId] [bigint] NULL,
	[NumberTestAssemblies] [bigint] NOT NULL,
	[NumberTestSuites] [bigint] NOT NULL,
	[NumberTestCase] [bigint] NOT NULL,
	[NumberScreenshots] [bigint] NOT NULL,
	[NumberFailedScreenshots] [bigint] NOT NULL,
	[BuildId] [bigint] NULL,
	[ParentObjId] [bigint] NULL,
	[Name] [nvarchar](700) NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_dbo.Builds] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]'

SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)


/****** Object:  Table [dbo].[ErrorMessages]    Script Date: 5/31/2016 8:42:14 PM ******/
SET @COMMAND_TEMPLATE='USE {DBNAME};
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE {DBNAME}.[dbo].[ErrorMessages](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Time] [datetime] NULL,
	[Code] [int] NOT NULL,
	[IsLastViewed] [bit] NOT NULL,
	[ExceptionMessage] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.ErrorMessages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'

SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)


/****** Object:  Table [dbo].[ImageWorkers]    Script Date: 5/31/2016 8:42:14 PM ******/
SET @COMMAND_TEMPLATE='USE {DBNAME};
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE {DBNAME}.[dbo].[ImageWorkers](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[WorkerServiceUrl] [nvarchar](600) NULL,
	[WorkerStatus] [int] NOT NULL,
	[Name] [nvarchar](700) NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_dbo.ImageWorkers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]'

SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)


/****** Object:  Table [dbo].[KeplerSystemConfigs]    Script Date: 5/31/2016 8:42:14 PM ******/
SET @COMMAND_TEMPLATE='USE {DBNAME};
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE {DBNAME}.[dbo].[KeplerSystemConfigs](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](500) NULL,
	[Value] [nvarchar](500) NULL,
 CONSTRAINT [PK_dbo.KeplerSystemConfigs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]'

SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)



/****** Object:  Table [dbo].[Projects]    Script Date: 5/31/2016 8:42:14 PM ******/
SET @COMMAND_TEMPLATE='USE {DBNAME};
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE {DBNAME}.[dbo].[Projects](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[MainBranchId] [bigint] NULL,
	[Name] [nvarchar](700) NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_dbo.Projects] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]'

SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)



/****** Object:  Table [dbo].[ScreenShots]    Script Date: 5/31/2016 8:42:14 PM ******/
SET @COMMAND_TEMPLATE='USE {DBNAME};
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE {DBNAME}.[dbo].[ScreenShots](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ImagePath] [nvarchar](700) NULL,
	[ImagePathUrl] [nvarchar](700) NULL,
	[PreviewImagePath] [nvarchar](700) NULL,
	[PreviewImagePathUrl] [nvarchar](700) NULL,
	[DiffImagePath] [nvarchar](1000) NULL,
	[DiffImagePathUrl] [nvarchar](1000) NULL,
	[DiffPreviewPath] [nvarchar](1000) NULL,
	[DiffPreviewPathUrl] [nvarchar](1000) NULL,
	[BaseLineImagePath] [nvarchar](700) NULL,
	[BaseLineImagePathUrl] [nvarchar](700) NULL,
	[BaseLinePreviewPath] [nvarchar](700) NULL,
	[BaseLinePreviewPathUrl] [nvarchar](700) NULL,
	[Url] [nvarchar](500) NULL,
	[BaseLineId] [bigint] NOT NULL,
	[IsLastPassed] [bit] NOT NULL,
	[ErrorMessage] [nvarchar](max) NULL,
	[BuildId] [bigint] NULL,
	[ParentObjId] [bigint] NULL,
	[Name] [nvarchar](700) NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_dbo.ScreenShots] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'

SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)



/****** Object:  Table [dbo].[TestAssemblies]    Script Date: 5/31/2016 8:42:14 PM ******/
SET @COMMAND_TEMPLATE='USE {DBNAME};
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE {DBNAME}.[dbo].[TestAssemblies](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[BuildId] [bigint] NULL,
	[ParentObjId] [bigint] NULL,
	[Name] [nvarchar](700) NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_dbo.TestAssemblies] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]'

SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)



/****** Object:  Table [dbo].[TestCases]    Script Date: 5/31/2016 8:42:14 PM ******/
SET @COMMAND_TEMPLATE='USE {DBNAME};
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE {DBNAME}.[dbo].[TestCases](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[BuildId] [bigint] NULL,
	[ParentObjId] [bigint] NULL,
	[Name] [nvarchar](700) NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_dbo.TestCases] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]'

SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)



/****** Object:  Table [dbo].[TestSuites]    Script Date: 5/31/2016 8:42:14 PM ******/
SET @COMMAND_TEMPLATE='USE {DBNAME};
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE {DBNAME}.[dbo].[TestSuites](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[BuildId] [bigint] NULL,
	[ParentObjId] [bigint] NULL,
	[Name] [nvarchar](700) NULL,
	[Status] [int] NOT NULL,
 CONSTRAINT [PK_dbo.TestSuites] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]'

SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)



USE [master]

SET @COMMAND_TEMPLATE='ALTER DATABASE {DBNAME} SET  READ_WRITE '
SET @SQL_SCRIPT = REPLACE(@COMMAND_TEMPLATE, '{DBNAME}', @DbName)
EXECUTE (@SQL_SCRIPT)

GO