//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kepler
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseLine : InfoObject
    {
        public BaseLine()
        {
            this.ScreenShots = new HashSet<ScreenShot>();
        }
    
    
        public virtual ICollection<ScreenShot> ScreenShots { get; set; }
        public virtual Project Project { get; set; }
    }
}
