//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kepler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Build : InfoObject
    {
        public Build()
        {
            this.TestAssemblies = new HashSet<TestAssembly>();
        }
    
        public long ProjectId { get; set; }
        public string Config { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<TestAssembly> TestAssemblies { get; set; }
    }
}
