//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kepler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project : InfoObject
    {
        public Project()
        {
            this.Builds = new HashSet<Build>();
        }
    
    
        public virtual ICollection<Build> Builds { get; set; }
        public virtual BaseLine BaseLine { get; set; }
    }
}
