//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kepler
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSuite : BuildObject
    {
        public TestSuite()
        {
            this.TestCases = new HashSet<TestCase>();
        }
    
        public long TestAssemblyId { get; set; }
    
        public virtual TestAssembly TestAssembly { get; set; }
        public virtual ICollection<TestCase> TestCases { get; set; }
    }
}
