//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kepler
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCase : BuildObject
    {
        public TestCase()
        {
            this.ScreenShots = new HashSet<ScreenShot>();
        }
    
        public long TestSuiteId { get; set; }
    
        public virtual TestSuite TestSuite { get; set; }
        public virtual ICollection<ScreenShot> ScreenShots { get; set; }
    }
}
